version: "3"

services:
  web:
    image: nginx
    volumes:
      - ./templates:/etc/nginx/templates
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./mime.types:/etc/nginx/mime.types
    ports:
      - "8080:8080"
  server1:
    image: carltonj2000/server
    volumes:
      - ./server:/app
    ports:
      - "3000-3010:3000"
    deploy:
      mode: replicated
      replicas: 3
